name: Build and Release

on:
  push:
    paths:
      - 'LoyalCompanion/**'
      - 'LoyalCompanion.sln'
      - '.github/workflows/build-release.yml'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    uses: Le-Vagabond-gh/FFXIV_Dalamud_Repo/.github/workflows/plugin-release.yml@main
    with:
      project: LoyalCompanion
    secrets: inherit
